#!/usr/bin/env node
import { Command } from 'commander';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { z } from 'zod';
import { HarnessConfigSchema, type HarnessConfig } from '../schemas/config.schema.js';
import { analyzeApp } from '../analyze.js';

const program = new Command();
const AnalyzeUrlSchema = z.string().url();
type AnalyzeMode = 'url-only' | 'url-repo';

async function loadConfigFile(relativePath: string): Promise<HarnessConfig> {
  const configPath = resolve(process.cwd(), relativePath);
  const configModule = await import(pathToFileURL(configPath).href);
  return HarnessConfigSchema.parse(configModule.default);
}

function redactConfigForLog(config: HarnessConfig): Record<string, unknown> {
  const base = { ...config } as Record<string, unknown>;
  if (config.auth?.type === 'form-login') {
    base.auth = {
      ...config.auth,
      credentials: {
        username: config.auth.credentials.username,
        password: '***',
      },
    };
  }
  return base;
}

async function runAnalyze(options: {
  url: string;
  repo?: string;
  configFile?: string;
  ephemeral?: boolean;
}): Promise<void> {
  const validatedUrl = AnalyzeUrlSchema.parse(options.url);
  const mode: AnalyzeMode = options.repo ? 'url-repo' : 'url-only';
  const config = await loadConfigFile(options.configFile ?? 'qulib.config.ts');
  const ephemeral = options.ephemeral ?? false;
  const writeArtifacts = !ephemeral;

  if (ephemeral) {
    console.error('[qulib] Ephemeral mode: no disk writes; full result JSON on stdout');
  } else {
    console.log('[qulib] Detected mode:', mode);
    console.log('[qulib] Active config:', redactConfigForLog(config));
  }

  const result = await analyzeApp({
    url: validatedUrl,
    repoPath: options.repo,
    config,
    writeArtifacts,
  });

  if (ephemeral) {
    console.log(
      JSON.stringify(
        {
          gapAnalysis: result.gapAnalysis,
          discoveredRoutes: result.routeInventory,
          repoInventory: result.repoInventory,
          decisionLog: result.decisionLog,
        },
        null,
        2
      )
    );
  }
}

program
  .name('qulib')
  .description('Qulib — QA harness')
  .version('0.1.0');

program
  .command('clean')
  .description('Remove all generated reports and scan state')
  .action(async () => {
    const fs = await import('node:fs/promises');
    const targets = ['output', '.scan-state'];
    for (const target of targets) {
      try {
        await fs.rm(target, { recursive: true, force: true });
        console.log(`[qulib] removed ${target}/`);
      } catch (err) {
        console.error(`[qulib] failed to remove ${target}/: ${String(err)}`);
      }
    }
    await fs.mkdir('output', { recursive: true });
    await fs.writeFile(
      'output/.gitkeep',
      'This folder is generated by `qulib analyze`. It contains report.json, report.md,\nand a `generated/` subfolder with test scaffolds. Run `qulib clean` to reset.\n',
      'utf8'
    );
    await fs.mkdir('.scan-state', { recursive: true });
    await fs.writeFile('.scan-state/.gitkeep', '', 'utf8');
    console.log('[qulib] clean complete');
  });

program
  .command('analyze')
  .description('Analyze an app for quality gaps')
  .requiredOption('--url <url>', 'Base URL of the app to analyze')
  .option('--repo <path>', 'Path to the app repo')
  .option('--prd <path>', 'Path to a PRD markdown file')
  .option('--config <file>', 'Path to config file (relative to cwd)', 'qulib.config.ts')
  .option(
    '--adapter <type>',
    'Override default test adapter (playwright, cypress-e2e, cypress-component, api)',
    'playwright'
  )
  .option('--ephemeral', 'Do not write to disk — return full report as JSON on stdout (use for MCP/CI)', false)
  .action(async (options) => {
    await runAnalyze({
      url: options.url,
      repo: options.repo,
      configFile: options.config,
      ephemeral: options.ephemeral,
    });
  });

program.parseAsync().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error('[qulib] Analyze failed:', message);
  process.exit(1);
});
